apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ns.yaml
# Argo CD & Argo CD ApplicationSet & Argo CD Notification
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.4/manifests/install.yaml
