---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreamkast
  labels:
    app: dreamkast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dreamkast
  template:
    metadata:
      labels:
        app: dreamkast
    spec:
      containers:
        - name: dreamkast
          image: kanatakita/appset-demo-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dreamkast
  labels:
    app: dreamkast
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dreamkast
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dreamkast
spec:
  rules:
    - host: IS_REPLACED
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-server
                port:
                  name: http
