apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base

generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.generated.resource: "true"
configMapGenerator:
- name: replacement-rules
  envs:
  - .env

replacements:
  - path: replacement_ingress-hostname.yaml
