apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.generated.resource: "true"
configMapGenerator:
- envs:
  - .env
  name: replacement-rules

replacements:
- path: replacement_ingress-hostname.yaml
resources:
- ../../../base
