apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: kustomize-with-replacements
      init:
        command: ["bash", "-euxc"]
        args:
        - export IFS=",";
          for image in ${IMAGES}; do
            kustomize edit set image $image;
          done;
      generate:
        command: ["kustomize", "build"]
      lockRepo: true
